Devel/danielatoh flori
andrei162/curs_vcgj_444D_flori pull request #5
Opened 2023-05-21 19:49 UTC by danielatoh

Am actualizat informatia din README.md

2023-05-21 21:57 UTC, andrei162 requested changes
Sa stergi fisierele deb si echo, nu stiu de ce se creeaza. Foloseste rm -rf <nume_fisier> in directorul care contine fisierele si apoi fa iar chestiunile cu git status, git add . , git commit -m "mesaj", git status, git push.

2023-05-22 11:50 UTC, danielatoh commented
Am sters fisierele deb si echo

2023-05-22 12:42 UTC, andrei162 approved these changes
Pare ok.

2023-05-22 14:11 UTC, maxirs8 reviewed
great

2023-05-22 14:12 UTC, maxirs8 approved these changes

2023-05-22 14:28 UTC, merged